### ISSUE TITLE
Source code does not build (on Linux)

### ISSUE THREAD

**Issue by treitmayr** [ankermake/AnkerMake-PrusaSlicer-Release#2]
I tried to build the AnkerMake Studio in its latest version (labeled [v1.5.10](https://github.com/ankermake/AnkerMake-PrusaSlicer-Release/releases/tag/v1.5.10)). While this was done for a Linux target using the steps presented in [How to build - Linux et al.md](https://github.com/ankermake/AnkerMake-PrusaSlicer-Release/blob/4c4856ea9c233975bb01e7085eeea3a6cda9e011/AnkerStudio/doc/How%20to%20build%20-%20Linux%20et%20al.md), I came across a lot of errors in the category of
* plain syntax errors (e.g. in src/slic3r/GUI/Common/AnkerGUIConfig.hpp)
* a lot of #includes missing
* multiple declarations of the same class AnkerBase

and warnings (where the indentation for if blocks with missing curly braces worried me the most).

After having fixed at least the errors, see https://github.com/treitmayr/AnkerMake-PrusaSlicer-Release/tree/fix-build, I was able to produce a binary application. However (and honestly as I expected) it was not able to fully start up. It showed a confirmation dialog for some usage conditions, then a confirmation dialog about detected global certificates, and then, before supposedly opening the main window, it seg-faulted with the following backtrace from gdb:
```
(ankermake studio:26857): Gtk-CRITICAL **: 11:37:20.165: gtk_window_resize: assertion 'height > 0' failed

Thread 1 "slic3r_main" received signal SIGSEGV, Segmentation fault.
0x00005555565e3b50 in Slic3r::GUI::Sidebar::enable_buttons(bool) ()
(gdb) bt
#0  0x00005555565e3b50 in Slic3r::GUI::Sidebar::enable_buttons(bool) ()
#1  0x00005555565f89c9 in Slic3r::GUI::Sidebar::Sidebar(Slic3r::GUI::Plater*) ()
#2  0x000055555661800c in Slic3r::GUI::Plater::priv::priv(Slic3r::GUI::Plater*, Slic3r::GUI::MainFrame*) ()
#3  0x000055555661bac6 in Slic3r::GUI::Plater::Plater(wxWindow*, Slic3r::GUI::MainFrame*) ()
#4  0x00005555565cc787 in Slic3r::GUI::MainFrame::init_tabpanel() ()
#5  0x00005555565d2198 in Slic3r::GUI::MainFrame::initTabPanel() ()
#6  0x00005555565d2eaa in Slic3r::GUI::MainFrame::MainFrame(int) ()
#7  0x000055555659c5c7 in Slic3r::GUI::GUI_App::on_init_inner() ()
#8  0x0000555557e728c3 in wxEntry(int&, wchar_t**) ()
#9  0x000055555657d123 in Slic3r::GUI::GUI_Run(Slic3r::GUI::GUI_InitParams&) ()
#10 0x0000555555bd46a2 in Slic3r::CLI::run(int, char**) ()
#11 0x0000555555b85da9 in main ()
```

Due to the high number of issues in the code I doubt that the provided code matches the AnkerMake Studio provided as binary releases. Therefore I would like to kindly ask for
* providing the up-to-date sources matching the 1.5.12 release,
* considering supporting x86_64 Linux builds.

**Comment by joscha** [comment]
References #6
